name: flutter_boilerplate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  dio: ^5.3.4

  # Firebase
  # firebase_core: ^2.24.0
  # firebase_analytics: ^10.5.1
  # firebase_crashlytics: ^3.4.6
  # TODO: integration needs to be completed later
  # Follow: https://firebase.google.com/docs/cloud-messaging/android/client
  # firebase_messaging: ^14.6.8

  # Riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Model Generator
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # # Image Utils
  # image_cropper: ^5.0.1
  # image_picker: ^1.0.2
  file_picker: ^ 9.2.3
  path_provider: ^2.1.3

  # Data persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # UI
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  string_validator: ^1.0.2

  # Utils
  intl: ^0.20.2
  skeletonizer: ^1.1.1
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_generator: ^3.1.0+1
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5

  # Linters and formatters
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0
  flutter_lints: ^5.0.0

dependency_overrides:
  source_gen: ^2.0.0
  analyzer: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/generated/
