name: flutter_boilerplate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  dio: ^5.3.4

  # Firebase
  # firebase_core: ^2.24.0
  # firebase_analytics: ^10.5.1
  # firebase_crashlytics: ^3.4.6
  # TODO: integration needs to be completed later
  # Follow: https://firebase.google.com/docs/cloud-messaging/android/client
  # firebase_messaging: ^14.6.8

  # Riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Model Generator
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # # Image Utils
  # image_cropper: ^5.0.1
  # image_picker: ^1.0.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3

  # data persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # UI
  # Cupertino Icons
  # Render SVG
  flutter_svg: ^2.0.9
  # Android toast
  fluttertoast: ^8.2.4
  # Collection of Google Fonts
  google_fonts: ^6.1.0
  string_validator: ^1.0.2

  # Utils
  intl: ^0.19.0
  skeletonizer: ^1.1.1
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.1
  # go_router_builder: ^2.3.3
  #The generator is now built in
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2

  # linters and formatters
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  very_good_analysis: ^5.0.0+1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/generated/
